# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df62d5ad00382aaa79d6a96f0c47a4374de1216e3271da28e8febc89afdb8cb72326889408021f85118c23a94b0338d71d9450c43644ca158c640a87e876bb6e

test:
  secret_key_base: 06125fdfc7ee1ee94b6b930772b6eaa6ba15a3fd0fc198bbcd733a457aebc4d6b8a5e73d5c3219071e2cb3be10ecb814caf4f9aa3346bf207a4c945680575867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
